POST http://localhost:8080/api/flight-routes
Content-Type: application/json

{
  "departureCity": "LHR",
  "arrivalCity": "AMS",
  "departureTime": "10:00:00",
  "arrivalTime": "11:00:00",
  "flightNumber": "BA"
}

### Get all flight routes
GET http://localhost:8080/api/flight-routes

### Get flight route by id
GET http://localhost:8080/api/flight-routes/1

### Update flight route
PUT http://localhost:8080/api/flight-routes/1
Content-Type: application/json

{
  "departureCity": "LHR",
  "arrivalCity": "Amsterdam",
  "departureTime": "10:00:00",
  "arrivalTime": "11:00:00",
  "flightNumber": "BA"
}


### Delete flight route
DELETE http://localhost:8080/api/flight-routes/3